# HW3 Q1 - Tensor Decomposition Reconstructions

In [1]:
import pandas as pd
import numpy as np
import tensorly as tl
from tensorly.decomposition import parafac, tucker
from tensorly.tenalg import outer
from itertools import product

In [2]:
lam = np.array([41.9075, 18.6722])
U1 = np.array([[0.6981, -0.4153],[0.1774, 0.7037],[0.6937, -0.5765]])
U2 = np.array([[0.6192, 0.8159],[0.3613, 0.2623],[0.6972, 0.5152]])
U3 = np.array([[0.6212, 0.6793],[0.5735, 0.6841],[0.5341, 0.2657]])
U4 = np.array([[0.6693, 0.5947],[0.7430, 0.8040]])

### Part 1a
**Write out the calculation of first outer product $U_{1,1} \circ U_{2,1}$**  
  
$U_{1,1} = \begin{bmatrix} 0.6981\\0.1774 \\0.6937\end{bmatrix}\;\;U_{2,1} = \begin{bmatrix} 0.6192\\0.3613\\0.6972\end{bmatrix}\;\;$  

$U_{1,1} \circ U_{2,1} \\
= \begin{bmatrix} 0.6981\\0.1774 \\0.6937\end{bmatrix} \circ \begin{bmatrix} 0.6192 & 0.3613 & 0.6972\end{bmatrix} \\
= \begin{bmatrix} 0.6981*0.6192 & 0.6981*0.3613 & 0.6981*0.6972 \\ 
                   0.1774*0.6192 & 0.1774*0.3613 & 0.1774*0.6972 \\ 
                   0.6937*0.6192 & 0.6937*0.3613 & 0.6937*0.6972 \end{bmatrix} \\
= \begin{bmatrix} 0.43226352 & 0.25222353 & 0.48671532 \\
                 0.10984608 & 0.06409462 & 0.12368328 \\
                 0.42953904 & 0.25063381 & 0.48364764 \end{bmatrix}$ 

### Part 1b
$\lambda_1U_{1,1} \circ U_{2,1} \circ U_{3,1} \circ U_{4,1}$

In [3]:
v1 = lam[0]*outer((outer((outer([U1[:,0], U2[:,0]]),U3[:,0])),U4[:,0]))
print(v1)

[[[[7.53169304 8.36104576]
   [6.95335795 7.71902727]
   [6.47565559 7.1887227 ]]

  [[4.39470396 4.87862699]
   [4.05724843 4.50401252]
   [3.77851157 4.19458254]]

  [[8.48045282 9.41427827]
   [7.82926544 8.69138536]
   [7.29138739 8.09427885]]]


 [[[1.91394119 2.12469491]
   [1.76697565 1.96154625]
   [1.64558273 1.82678614]]

  [[1.11677479 1.2397485 ]
   [1.03102116 1.1445521 ]
   [0.96018902 1.06592027]]

  [[2.15503843 2.39234059]
   [1.98955979 2.20864026]
   [1.85287512 2.05690455]]]


 [[[7.48422212 8.30834757]
   [6.90953217 7.67037562]
   [6.43484068 7.14341346]]

  [[4.36700493 4.84787787]
   [4.03167631 4.47562453]
   [3.75469628 4.16814484]]

  [[8.42700203 9.35494175]
   [7.77991897 8.6366051 ]
   [7.24543108 8.04326205]]]]


$\lambda_2U_{1,2} \circ U_{2,2} \circ U_{3,2} \circ U_{4,2}$

In [4]:
v2 = lam[1]*outer((outer((outer([U1[:,1], U2[:,1]]),U3[:,1])),U4[:,1]))
print(v2)

[[[[-2.55595915 -3.45550892]
   [-2.5740198  -3.47992588]
   [-0.99973259 -1.35158063]]

  [[-0.82170374 -1.11089593]
   [-0.82750998 -1.11874563]
   [-0.32139951 -0.43451354]]

  [[-1.61396023 -2.18198087]
   [-1.62536463 -2.19739896]
   [-0.63128107 -0.8534555 ]]]


 [[[ 4.33091368  5.85514478]
   [ 4.36151634  5.8965178 ]
   [ 1.69398464  2.29016924]]

  [[ 1.39232585  1.88234401]
   [ 1.40216416  1.89564483]
   [ 0.54459146  0.73625615]]

  [[ 2.73475515  3.69723077]
   [ 2.7540792   3.72335577]
   [ 1.06966649  1.44612721]]]


 [[[-3.54806272 -4.79677556]
   [-3.57313368 -4.83067005]
   [-1.38778193 -1.87620089]]

  [[-1.14065063 -1.54209368]
   [-1.14871058 -1.55299026]
   [-0.44615173 -0.60317134]]

  [[-2.24042397 -3.02892361]
   [-2.25625502 -3.05032627]
   [-0.87631481 -1.18472693]]]]


$\chi$ - the full reconstruction  
$\chi = \lambda_1U_{1,1} \circ U_{2,1} \circ U_{3,1} \circ U_{4,1} + \lambda_2U_{1,2} \circ U_{2,2} \circ U_{3,2} \circ U_{4,2}$

In [5]:
X = v1 + v2
print(X)

[[[[4.97573389 4.90553684]
   [4.37933814 4.23910139]
   [5.475923   5.83714207]]

  [[3.57300022 3.76773106]
   [3.22973844 3.38526689]
   [3.45711206 3.760069  ]]

  [[6.86649259 7.23229739]
   [6.20390081 6.4939864 ]
   [6.66010632 7.24082335]]]


 [[[6.24485487 7.97983969]
   [6.12849198 7.85806405]
   [3.33956736 4.11695539]]

  [[2.50910064 3.12209251]
   [2.43318532 3.04019693]
   [1.50478047 1.80217642]]

  [[4.88979358 6.08957136]
   [4.74363899 5.93199602]
   [2.92254161 3.50303177]]]


 [[[3.9361594  3.51157201]
   [3.33639849 2.83970557]
   [5.04705875 5.26721256]]

  [[3.22635429 3.3057842 ]
   [2.88296573 2.92263427]
   [3.30854455 3.5649735 ]]

  [[6.18657807 6.32601814]
   [5.52366395 5.58627883]
   [6.36911627 6.85853512]]]]


### Part 2
**Compute the reconstruction of the Tucker decomposition.**

In [6]:
G11 = np.array([[35.2489, 0.7832],[0.2884, -4.2162]])
G21 = np.array([[0.3406, 2.0238],[-1.6475, -2.4122]])
G12 = np.array([[0.0883, -1.4479],[0.9827, 3.4852]])
G22 = np.array([[1.0571, -3.3204],[4.3714, -7.8907]])
U1 = np.array([[0.6276,-0.0110],[80.5511, -0.7],[0.5499, 0.7141]])
U2 = np.array([[0.5840, 0.6977],[0.3660, 0.23],[0.7246, -0.6785]])
U3 = np.array([[0.6157, -0.4874],[0.5428, 0.8319],[0.5712, -0.2651]])
U4 = np.array([[0.6827, 0.7307],[0.7307, -0.6827]])

In [7]:
core = np.array([[[35.2489, 0.7832],[0.2884, -4.2162]], [[0.0883, -1.4479],[0.9827, 3.4852]], [[0.3406, 2.0238],[-1.6475, -2.4122]], [[1.0571, -3.3204],[4.3714, -7.8907]]])
core.shape

(4, 2, 2)

In [8]:
core = np.zeros([2,2,2,2])
core[0,0,:,:] = G11
core[1,0,:,:] = G12
core[0,1,:,:] = G21
core[1,1,:,:] = G22

In [9]:
tl.tucker_to_tensor((core, [U1, U2, U3, U4]))

array([[[[  7.16409542,   4.74824783],
         [  3.38817996,   5.78954063],
         [  6.21218188,   4.64283751]],

        [[  4.17041786,   3.08932083],
         [  2.30763958,   3.68045675],
         [  3.66600009,   3.00793363]],

        [[  6.50911262,   6.73730222],
         [  5.57647095,   7.57141737],
         [  6.01464889,   6.49233295]]],


       [[[918.74089459, 608.88560844],
         [434.14448847, 747.10275307],
         [796.61124464, 596.06364018]],

        [[534.74561614, 396.50910845],
         [296.2064984 , 473.60633606],
         [470.11378933, 386.24498443]],

        [[834.15691814, 866.58642681],
         [718.39360561, 967.11242866],
         [771.34738059, 834.0745027 ]]],


       [[[  5.50927833,   3.60961442],
         [  2.23557238,   9.16792806],
         [  4.72238311,   4.23630735]],

        [[  3.12694362,   2.70834679],
         [  2.0483356 ,   4.47302962],
         [  2.79590253,   2.82182337]],

        [[  4.40835854,   7.80274221],
     

### Part 3
**Calculate the MSE for CP and Tucker decompositions. Briefly discuss the difference, especially regarding the relative reduction of features for each method.** 

In [10]:
X = np.zeros([2,3,3,3])
X[0,0,:,:] = np.matrix([[4, 2, 6],[5, 2, 9],[6, 7, 2]])
X[0,1,:,:] = np.matrix([ [4, 3, 6],[8, 4, 1],[4, 2, 9] ])
X[0,2,:,:] = np.matrix([ [6, 3, 8], [0, 4, 5], [3, 2, 7] ])
X[1,0,:,:] = np.matrix([ [4, 5, 8], [7, 3, 6],[2, 4, 9] ])
X[1,1,:,:] = np.matrix([ [5, 1, 8], [8, 3, 6],[3, 5, 1] ])
X[1,2,:,:] = np.matrix([[9, 3, 5],[7, 2, 0],[4, 2, 9] ])
n = X.shape[0]*X.shape[1]*X.shape[2]*X.shape[3]

In [11]:
# CP Decomposition with optimal R
CP_decomp = tl.decomposition.parafac(X,1)
CP_X = tl.kruskal_to_tensor(CP_decomp)  
cp_mse = np.sum((X - CP_X)**2)/n

In [12]:
# Tucker Decomposition
core, factors = tl.decomposition.tucker(X, rank=[2,2,2,2])
tucker_X = tl.tucker_to_tensor((core, factors))
tucker_mse = np.sum((X - tucker_X)**2)/n

In [13]:
CP_decomp[1][0].shape,CP_decomp[1][1].shape,CP_decomp[1][2].shape,CP_decomp[1][3].shape

((2, 1), (3, 1), (3, 1), (3, 1))

In [14]:
factors[0].shape, factors[1].shape, factors[2].shape, factors[3].shape

((2, 2), (3, 2), (3, 2), (3, 2))

In [15]:
print("MSE for CP Decomposition = " + str(round(cp_mse,5)))
print("MSE for Tucker Decomposition = " + str(round(tucker_mse,5)))
print("Tucker decomposition provides a smaller MSE and a smaller number of features. CP decomposition contains 54 elements (2x3x3x3) while Tucker decomposition contains 22 elements (2*2+3*2+3*2+3*2).")

MSE for CP Decomposition = 4.98583
MSE for Tucker Decomposition = 2.62176
Tucker decomposition provides a smaller MSE and a smaller number of features. CP decomposition contains 54 elements (2x3x3x3) while Tucker decomposition contains 22 elements (2*2+3*2+3*2+3*2).
